server:
  port: 8085


spring:
  jpa:
    hibernate:
      ddlAuto: create

  datasource:
    url: jdbc:mysql://localhost:3306/course-erp-db
    username: root
    password: 1312acab
    driverClassName: com.mysql.cj.jdbc.Driver

security:
  jwt:
    public-key:
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApBQy0RjLCG+vazYPrAWboYhPVar/KJxJTveAj7YnqYT/zyNt8+02p4N0CwcgjpsSZ9n8qKPSSYuYVn01pQ95hYhYJTsIg5EuUlPhUaf3/0kbEsumEarwNJOt06X5Hayn5ZBgVeA2BbJkx07borZkWcYQL85SqR8CSPHafrycnF4Mb2eFv1jfafn7Sb3Jzxawr77LTPtiM4g5Tf2SZ0LxqY1P2TepsaHMDj6J3ClCOzrdAHGXn5tYx4kgbo5GMdLjcy+0ZSSVt9JB4KjvfxC4VylIxBSvetGiY756Zdiplv2fcFW8xGCQbl1efwWppKl9fRN8BbgjLyLx2WF9Z8VAYwIDAQAB
    private-key:
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkFDLRGMsIb69rNg+sBZuhiE9Vqv8onElO94CPtiephP/PI23z7Tang3QLByCOmxJn2fyoo9JJi5hWfTWlD3mFiFglOwiDkS5SU+FRp/f/SRsSy6YRqvA0k63TpfkdrKflkGBV4DYFsmTHTtuitmRZxhAvzlKpHwJI8dp+vJycXgxvZ4W/WN9p+ftJvcnPFrCvvstM+2IziDlN/ZJnQvGpjU/ZN6mxocwOPoncKUI7Ot0AcZefm1jHiSBujkYx0uNzL7RlJJW30kHgqO9/ELhXKUjEFK960aJjvnpl2KmW/Z9wVbzEYJBuXV5/BamkqX19E3wFuCMvIvHZYX1nxUBjAgMBAAECggEAI2aoQC0VQVC3jG4xm2/qUEPUuisWunBd8Me92UP38r9bYhnG02ZO8H2QQADdqWcT5YxG0yvlZzDTQXXqaR6ZnZH5Uq8V+y0LzX+Dkdanz1C6oqeFwTIceXuTeaLJyPlDkGhCIMUrYrdGvynogYbQx/3P6ECf3RVvrMVh2w5ey+22HWvM4MEG4h4j9W+EUbAfNblH1B1BGPZKJaGZ4dHy7TLO6D7MifJaV/Ace63kF9igH0owi/Gr+U4ALc25qBYHOpb2lD5177Zof/Qq1f8RN6dO6BEUBr/kklV4PzAeIpf17zV3IIjNj6fQ5S+0HJv/2iTlS5dFbMvwdOqd0p3VYQKBgQC+prCj18xcoOFNe1NHG9Tae0kMoFQKEcwN9vL6k13F3ht/Je8dBpfrFuXn1Fs2/b2kTLX9pdGE3lnO+zV/g/z3+s5XB8kBnA115xvCpNHqX1KhNI2dk1QNxpE8EfiGhixMp/d51xylxcuzbQ6NRZRspcTFh4/lM1AZZrp2VWP6jQKBgQDcUdc2Qx++nmxbeVVnqo8XWSrV983+b/VS4czUKbbhzFrIwFw7sMecRZYb160GbdoQE6VMqpg49BWVKmL/NIpBM+euIDexG+hHMEmz8lOH0U1f8y0NRcf3f2At8vkGaUZ8umb7V0mZipAQp8nl6Cs3sOl7UWRnVWF80p+8dU9irwKBgQCGNaPNgyGK53oTaEikmzQJJZaz+72NZR/niLtdqBXwL73dkR+1qCmTxgfMXlJj8NXqblIDIBLRXRGNwovTm1+eVgGhhIp8xpU3NZz2Nb7MJZRuhSdYERmvpOQijGgOky9mOyvcqpCxJf+S7Ke8zYmBvmQ5xYeHisrNRuLmYJBEFQKBgDbq74pHERKiyr/Cbtd4XFKll1fefSp/HdebEUORYlTGa5q+2D7IwfjiH5ixGiAQIdsACqQhofAQZ5DXD/YtUokONyHgRgGPw0Z7cuO387pXIcJZC1HToxS+W2sYtZozg65ziFf+Wgo7z81XBayZQqyPHKPwleZsEfDbT5XaZ/9hAoGADiBNh6dw9s/L5kIW40PF4GWALQT6lqNcJQwxQATdF6LlmYwwISkWAUAI1CnQC75oB+qqO1Ta6ov8z7L+I6Ci7lqnfT6E8/FkoC6WWNUn3/99ktcePZeSe82ZAkRf0ftsSI86wFm93gvAzJCUeUWTDBYl4q2/ZvattZkMCzU5BiA=
    access-token-validity-time: 1800000
    refresh-token-validity-time: 86400000
